In [5]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("../cell_counts.db")

# Independent check of Part 4 headline number, hand-written SQL (not reusing src/ code).
query = """
SELECT cc.cell_count
FROM cell_counts cc
JOIN samples sm ON cc.sample_id = sm.sample_id
JOIN subjects subj ON sm.subject_id = subj.subject_id
WHERE subj.condition = 'melanoma' AND subj.treatment = 'miraclib' AND sm.sample_type = 'PBMC'
  AND sm.time_from_treatment_start = 0 AND subj.sex = 'M' AND subj.response = 'yes'
  AND cc.population = 'b_cell'
"""
b_cells = pd.read_sql(query, conn)
len(b_cells), round(b_cells["cell_count"].mean(), 2)

(184, np.float64(10401.28))

In [6]:
cohort_summary = pd.read_csv("../outputs/subset_cohort_counts.csv")
cohort_summary

                  metric group  value
0    samples_per_project  prj1    384
1    samples_per_project  prj3    272
2  subjects_per_response    no    325
3  subjects_per_response   yes    331
4       subjects_per_sex     F    312
5       subjects_per_sex     M    344

In [7]:
population_summary = pd.read_csv("../outputs/subset_population_means.csv")
population_summary

   sex response  population  mean_cell_count
0    F       no      b_cell          9421.38
1    F       no  cd4_t_cell         29334.13
2    F       no  cd8_t_cell         24369.99
3    F       no    monocyte         19871.75
4    F       no     nk_cell         14927.50
5    F      yes      b_cell         10100.63
6    F      yes  cd4_t_cell         31200.14
7    F      yes  cd8_t_cell         25144.59
8    F      yes    monocyte         20042.67
9    F      yes     nk_cell         15327.78
10   M       no      b_cell          9756.51
11   M       no  cd4_t_cell         29233.65
12   M       no  cd8_t_cell         24703.84
13   M       no    monocyte         19803.86
14   M       no     nk_cell         14844.59
15   M      yes      b_cell         10401.28
16   M      yes  cd4_t_cell         29976.71
17   M      yes  cd8_t_cell         25339.43
18   M      yes    monocyte         20432.82
19   M      yes     nk_cell         15601.77